apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      subapp: freshrss

helmCharts:
  - releaseName: freshrss
    name: freshrss
    repo: https://k8s-home-lab.github.io/helm-charts/
    valuesFile: values.yaml

resources:
  - pv.yaml
