apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-config-pv
  labels:
    type: config
spec:
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - homelab
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/homelab/rss/freshrss/config
  storageClassName: local-persistent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-config-pvc
spec:
  selector:
    matchLabels:
      type: config
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-persistent
