apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab

labels:
  - includeSelectors: true
    pairs:
      app: n8n

helmCharts:
  - releaseName: n8n
    name: n8n
    repo: https://community-charts.github.io/helm-charts
    valuesFile: values.yaml

# resources:
#   - pv.yaml
