apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n

labels:
  - includeSelectors: true
    pairs:
      app: n8n

secretGenerator:
  - name: postgresql-credentials
    envs:
      - credentials.env

helmCharts:
  - releaseName: n8n
    name: n8n
    repo: https://community-charts.github.io/helm-charts
    valuesFile: values.yaml

# resources:
#   - pv.yaml
resources:
  - namespace.yaml
