apiVersion: v1
kind: PersistentVolume
metadata:
  name: das-db-data-pv
  labels:
    from: das-db
    type: data
spec:
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - homelab
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/das/das-db/data
  storageClassName: local-persistent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: das-db-data-pvc
spec:
  selector:
    matchLabels:
      from: das-db
      type: data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-persistent
