apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-limits
  namespace: monitoring
spec:
  hard:
    limits.cpu: "1"
    limits.memory: "4Gi"
