apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

labels:
  - includeSelectors: true
    pairs:
      app: pihole

secretGenerator:
  - name: pihole-credentials
    envs:
      - credentials.env

helmCharts:
  - releaseName: pihole
    name: pihole
    repo: https://mojo2600.github.io/pihole-kubernetes/
    valuesFile: values.yaml

resources:
  - namespace.yaml
  - pv.yaml
