apiVersion: v1
kind: Namespace
metadata:
  name: speedtest
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-limits
  namespace: speedtest
spec:
  hard:
    limits.cpu: "1"
    limits.memory: "4Gi"
