---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud
        ports:
        - containerPort: 80
          name: nextcloud-web
        env:
          - name: PHP_UPLOAD_LIMIT
            value: 256G
          - name: PHP_MEMORY_LIMIT
            value: 8G
        volumeMounts:
          - mountPath: /var/www/html
            name: nextcloud-config
            subPath: .
      volumes:
        - name: nextcloud-config
          persistentVolumeClaim:
            claimName: nextcloud-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      name: nextcloud-web
      port: 80
      targetPort: nextcloud-web
---
