apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

labels:
- includeSelectors: true
  pairs:
    app: nextcloud

secretGenerator:
  - name: nextcloud-credentials
    envs:
      - credentials.env
  - name: db-credentials
    envs:
      - db-credentials.env

resources:
  - namespace.yaml
  - pv.yaml
  - deployment.yaml
  - ingress.yaml
