apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab

labels:
- includeSelectors: true
  pairs:
    app: nextcloud

secretGenerator:
  - name: nextcloud-credentials
    envs:
      - credentials.env

helmCharts:
  - releaseName: nextcloud
    name: nextcloud
    repo: https://nextcloud.github.io/helm/
    valuesFile: values.yaml
