apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  # It has really weird formating with the 4-wide tabs
  # But follow it. It does'nt work on 2-wide tabs
  # siteMonitor = ping the service to see if it's up
  # use siteMonitor for URLs and ping for Ips/Hostname
  services.yaml: |
    - Monitoring:
        - Grafana:
            href: http://grafana.localhost:8081/
            description: Homepage is awesome
            icon: grafana.svg
            siteMonitor: http://grafana.grafana.svc.cluster.local

        - Prometheus:
            href: http://prometheus.localhost:8081/
            icon: prometheus.svg
            siteMonitor: http://prometheus-server.prometheus.svc.cluster.local

    - Services:
        - Nextcloud:
            href: http://nextcloud.localhost:8081/login
            description: Homepage is the best
            icon: nextcloud.svg
            siteMonitor: http://nextcloud.nextcloud.svc.cluster.local

        - Jenkins:
            href: http://jenkins.localhost:8081/login
            icon: jenkins.svg
            siteMonitor: http://jenkins.jenkins.svc.cluster.local:8080

        - Pihole:
            href: http://pihole.localhost:8081/admin/login
            icon: pi-hole.svg
            siteMonitor: http://pihole-web.pihole.svc.cluster.local

        - Jellyfin:
            href: http://jellyfin.localhost:8081
            icon: jellyfin.svg
            siteMonitor: http://jellyfin.jellyfin.svc.cluster.local

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
