apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  # It has really weird formating with the 4-wide tabs
  # But follow it. It does'nt work on 2-wide tabs
  services.yaml: |
    - Monitoring:
        - Grafana:
            href: http://grafana.localhost:8081/
            description: Homepage is awesome

        - Prometheus:
            href: http://prometheus.localhost:8081/

    - Services:
        - Nextcloud:
            href: http://nextcloud.localhost:8081/
            description: Homepage is the best

        - Jenkins:
            href: http://jenkins.localhost:8081/

        - Pihole:
            href: http://pihole.localhost:8081/

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
