apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: freshrss
  name: freshrss
  namespace: rss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
      - image: freshrss/freshrss
        name: freshrss-container
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss
  namespace: rss
spec:
  selector:
    app: freshrss
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freshrss
  namespace: rss
  labels:
    app.kubernetes.io/name: freshrss
spec:
  rules:
    - host: "freshrss.localhost"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: freshrss
                port:
                  number: 80
