apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab

labels:
  - includeSelectors: true
    pairs:
      app: rss

resources:
  - fivefilters.yaml

helmCharts:
  - releaseName: freshrss
    name: freshrss
    repo: https://k8s-home-lab.github.io/helm-charts/
    valuesFile: freshrss-values.yaml
