apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rss

labels:
  - includeSelectors: true
    pairs:
      app: rss

resources:
  - namespace.yaml
  - freshrss
  - fivefilters
