apiVersion: v1
kind: Namespace
metadata:
  name: rss
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-limits
  namespace: rss
spec:
  hard:
    limits.cpu: "1"
    limits.memory: "4Gi"
