apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twingate

labels:
  - includeSelectors: true
    pairs:
      app: twingate

secretGenerator:
  - name: twingate-credentials
    envs:
      - credentials.env

helmCharts:
  - releaseName: twingate
    name: connector
    repo: https://twingate.github.io/helm-charts
    valuesFile: values.yaml

resources:
  - namespace.yaml
