apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adminer

labels:
  - includeSelectors: true
    pairs:
      app: adminer

helmCharts:
  - releaseName: adminer
    name: adminer
    repo: https://charts.ectobit.com
    valuesFile: values.yaml

resources:
  - namespace.yaml
