apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: firefly

labels:
  - includeSelectors: true
    pairs:
      app: firefly

secretGenerator:
  - name: firefly-credentials
    envs:
      - credentials.env
  - name: importer-token
    envs:
      - importer-token.env

helmCharts:
  - releaseName: firefly
    name: firefly-iii
    repo: https://firefly-iii.github.io/kubernetes
    valuesFile: values.yaml

  - releaseName: firefly-importer
    name: importer
    repo: https://firefly-iii.github.io/kubernetes
    valuesFile: importer-values.yaml

resources:
  - namespace.yaml
  - pv.yaml
