apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

labels:
  - includeSelectors: true
    pairs:
      app: ingress


helmCharts:
  - releaseName: nginx
    name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    valuesFile: values.yaml

# resources:
#   - tcp-services.yaml
#   - udp-services.yaml
