apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab


labels:
  - includeSelectors: true
    pairs:
      app: jellyfin

# secretGenerator:
#   - name: lgtm-grafana
#     envs:
#       - credentials.env

helmCharts:
  - releaseName: jellyfin
    name: jellyfin
    repo: https://djjudas21.github.io/charts/
    valuesFile: values.yaml
