# jellyfin:
#   mediaVolumes:
#     - /media

ingress:
  enabled: true
  hostname: jellyfin.localhost
  # extraHosts:
  #   - jellyfin.vitekborovsky.twingate.com
  path: /
  pathType: Prefix



presistance:
  cache:
    enabled: false

  config:
    enabled: false
