existingClaim: true
jellyfin:
  mediaVolumes:
    - name: music
      readOnly: true
      existingClaim: "media-pvc"
      volumeSpec:
        accessModes:
          - ReadWriteOnce
        capacity:
          storage: 1Gi

ingress:
  enabled: true
  hostname: jellyfin.localhost
  # extraHosts:
  #   - jellyfin.vitekborovsky.twingate.com
  path: /
  pathType: Prefix


presistance:
  cache:
    enabled: false

  config:
    enabled: false
