apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab

labels:
  - includeSelectors: true
    pairs:
      app: mysql


# secretGenerator:
#   - name: grafana-credentials
#     envs:
#       - credentials.env

helmCharts:
  - releaseName: mysql
    name: mysql
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
