apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ollama

labels:
  - includeSelectors: true
    pairs:
      app: ollama

helmCharts:
  - releaseName: ollama
    name: ollama
    repo: https://otwld.github.io/ollama-helm/
    valuesFile: values.yaml

resources:
  - namespace.yaml
