- Monitoring:
    - Grafana:
        href: http://grafana.homelab/
        description: Homepage is awesome
        icon: grafana.svg
        siteMonitor: http://lgtm-grafana.monitoring.svc.cluster.local

    - Prometheus:
        href: http://prometheus.homelab/
        icon: prometheus.svg
        siteMonitor: http://prometheus-server.monitoring.svc.cluster.local

    - Adminer:
        href: http://adminer.homelab/
        icon: adminer.svg
        siteMonitor: http://adminer.adminer.svc.cluster.local


- Services:
    - Nextcloud:
        href: http://nextcloud.homelab/login
        description: Homepage is the best
        icon: nextcloud.svg
        siteMonitor: http://nextcloud.nextcloud.svc.cluster.local

    - Jenkins:
        href: http://jenkins.homelab/login
        icon: jenkins.svg
        siteMonitor: http://jenkins.jenkins.svc.cluster.local:8080

    - Pihole:
        href: http://pihole.homelab/admin/login
        icon: pi-hole.svg
        siteMonitor: http://pihole-web.pihole.svc.cluster.local

    - Jellyfin:
        href: http://jellyfin.homelab
        icon: jellyfin.svg
        siteMonitor: http://jellyfin.jellyfin.svc.cluster.local

    - Firefly:
        href: http://firefly.homelab
        icon: firefly.svg
        siteMonitor: http://firefly-firefly-iii.firefly.svc.cluster.local
- Rss:
    - Five Filters:
        href: http://fivefilters.homelab
        icon: rsshub.png # TODO bad icon
        siteMonitor: http://fivefilters.rss.svc.cluster.local

    - Fresh RSS:
        href: http://freshrss.homelab
        icon: freshrss.svg
        siteMonitor: http://freshrss.rss.svc.cluster.local

- Automation:
    - N8n:
        href: http://n8n.homelab
        icon: n8n.svg
        siteMonitor: http://n8n.n8n.svc.cluster.local
